### ISSUE TITLE
Query option incorrectly states Spool Manager is installed

### ISSUE THREAD

**Issue by evannadeau** [tkoecker/OctoPrint-Mmu2filamentselect#7]
Hello, and thank you very VERY much for this new feature.

I've tested it, and it does work correctly when I select Query from Filamanet Manager.  However, it does also state that Spool Manager is installed.  I believe I may have had it installed in the past and removed it.  I checked the plugin cleanup area, and there is nothing there.

Whatever query is being made to see if the plugin is installed, must be finding some remnants of the previous install.  I had thought perhaps there were some common components, so I tried selecting Spool Manager, however, it then defaulted to the manual entry names.

![image](https://user-images.githubusercontent.com/1878498/120692660-4eefa000-c465-11eb-8bdf-1bfb350a1a28.png)

Please let me know what else I can provide to diagnose this issue.

**Comment by tkoecker** [comment]
Thanks for the report. The detection of the installed plugins in the settings dialog was broken.
It should now be fixed in 1.0.6.
