### ISSUE TITLE
Feature request: Sensor and MMU2S Status

### ISSUE THREAD

**Issue by buzz-b** [tkoecker/OctoPrint-Mmu2filamentselect#8]
Hi,

I was wondering if you have access in the plugin to the MMU2S sensor status?, I'd like to get this information through eventually to OctoDash (& HASS), so you can easily see if there are unload errors caused by the filament sensor, etc?

Thanks,
Andy...

**Comment by tkoecker** [comment]
Sorry, I guess thats currently not possible. To my knowledge there is no g-code to query that status. See also https://community.octoprint.org/t/reading-sensor-status-from-a-prusa-printer-mk3s-mmu2s/22033
